---
- name: top
  block:
    - name: Copy ~/.toprc
      ansible.builtin.copy:
        src: "{{ lookup('first_found', params) }}"
        dest: ~/.toprc
        mode: 0644
        force: true
        backup: true
      vars:
        params:
          files:
            - toprc-{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}
            - toprc
  when:
    - ansible_facts.os_family in ["Debian"]
    - ansible_facts.distribution_major_version | int in [6, 7, 8, 9, 10, 11, 12]
  tags:
    - dotfiles
    - dotfiles-top
