---
- name: dotfiles
  block:
    - name: Include dotfiles_bash
      include_role:
        name: dotfiles_bash
        apply:
          tags:
            - dotfiles
            - dotfiles-bash
      tags:
        - dotfiles
        - dotfiles-bash

    - name: Include dotfiles_htop
      include_role:
        name: dotfiles_htop
        apply:
          tags:
            - dotfiles
            - dotfiles-htop
      tags:
        - dotfiles
        - dotfiles-htop

    - name: Include dotfiles_nano
      include_role:
        name: dotfiles_nano
        apply:
          tags:
            - dotfiles
            - dotfiles-nano
      tags:
        - dotfiles
        - dotfiles-nano

    - name: Include dotfiles_screen
      include_role:
        name: dotfiles_screen
        apply:
          tags:
            - dotfiles
            - dotfiles-screen
      tags:
        - dotfiles
        - dotfiles-screen

    - name: Include dotfiles_top
      include_role:
        name: dotfiles_top
        apply:
          tags:
            - dotfiles
            - dotfiles-top
      tags:
        - dotfiles
        - dotfiles-top

    - name: Include dotfiles_vim
      include_role:
        name: dotfiles_vim
        apply:
          tags:
            - dotfiles
            - dotfiles-vim
      tags:
        - dotfiles
        - dotfiles-vim
