---
- name: bash
  block:
    - name: Remove legacy BASH dotfiles
      include_tasks:
        file: remove_legacy.yml
        apply:
          tags:
            - bash
            - bash-remove-legacy
      tags:
        - bash
        - bash-remove-legacy

    - name: Install BASH dotfiles
      include_tasks:
        file: install_bash.yml
        apply:
          tags:
            - bash
            - bash-install
      tags:
        - bash
        - bash-install
  when:
    - ansible_facts.os_family in ["Debian"]
    - ansible_facts.distribution_major_version | int in [9, 10, 11]
  tags:
    - bash
