---
- name: bash
  block:
    - name: Install BASH dotfiles
      include_tasks:
        file: install_bash.yml
        apply:
          tags:
            - dotfiles
            - dotfiles-bash
            - dotfiles-bash-install
      tags:
        - dotfiles
        - dotfiles-bash
        - dotfiles-bash-install

    - name: Remove legacy BASH dotfiles
      include_tasks:
        file: remove_legacy.yml
        apply:
          tags:
            - dotfiles
            - dotfiles-bash
            - dotfiles-bash-remove-legacy
      tags:
        - dotfiles
        - dotfiles-bash
        - dotfiles-bash-remove-legacy
  when:
    - ansible_facts.os_family in ["Debian"]
    - ansible_facts.distribution_major_version | int in [9, 10, 11]
  tags:
    - dotfiles
    - dotfiles-bash
