---
- name: bash # noqa: name[casing]
  when:
    - ansible_facts.os_family in ["Debian"]
    - ansible_facts.distribution_major_version | int in [9, 10, 11, 12]
  tags:
    - dotfiles
    - dotfiles-bash
  block:
    - name: Install BASH dotfiles
      ansible.builtin.import_tasks:
        file: install_bash.yml
      tags:
        - dotfiles
        - dotfiles-bash
        - dotfiles-bash-install

    - name: Remove legacy BASH dotfiles
      ansible.builtin.import_tasks:
        file: remove_legacy.yml
      tags:
        - dotfiles
        - dotfiles-bash
        - dotfiles-bash-remove-legacy
