---
- name: screen
  block:
    - name: Copying ~/.screenrc
      ansible.builtin.copy:
        src: "{{ lookup('first_found', params) }}"
        dest: ~/.screenrc
        mode: 0644
        force: true
        backup: true
      vars:
        params:
          files:
            - screenrc-{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}
            - screenrc
  when:
    - ansible_facts.os_family in ["Debian"]
    - ansible_facts.distribution_major_version | int in [6, 7, 8, 9, 10, 11]
  tags:
    - dotfiles
    - dotfiles-screen
