---
- name: htop
  block:
    - name: Creating ~/.config/htop/ directory
      ansible.builtin.file:
        path: ~/.config/htop/
        state: directory
        mode: 0755

    - name: Copying ~/.config/htop/htoprc
      ansible.builtin.copy:
        src: "{{ lookup('first_found', params) }}"
        dest: ~/.config/htop/htoprc
        mode: 0644
        force: true
        backup: true
      vars:
        params:
          files:
            - htoprc-{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}
            - htoprc
  when:
    - ansible_facts.os_family in ["Debian"]
    - ansible_facts.distribution_major_version | int in [7, 8, 9, 10, 11]
  tags:
    - dotfiles-htop
