---
- name: nano # noqa: name[casing]
  when:
    - ansible_facts.os_family in ["Debian"]
    - ansible_facts.distribution_major_version | int in [6, 7, 8, 9, 10, 11, 12, 13]
  tags:
    - dotfiles
    - dotfiles-nano
  block:
    - name: Copy ~/.nanorc
      ansible.builtin.copy:
        src: "{{ lookup('first_found', params) }}"
        dest: ~/.nanorc
        mode: "0644"
        force: true
        backup: true
      vars:
        params:
          files:
            - nanorc-{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}
            - nanorc
