name: Ansible Lint

on:  # yamllint disable-line rule:truthy
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.2.1
